"""fix_appointment_client_id_type

Revision ID: 0446b11066dc
Revises: 231149caa599
Create Date: 2026-02-15 21:42:54.621587

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0446b11066dc'
down_revision = '231149caa599'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('data_hora', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column('duracao', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('observacoes', sa.Text(), nullable=True))
    op.alter_column('appointments', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('appointments', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='appointmentstatus'),
               nullable=False)
    op.drop_column('appointments', 'date_time')
    op.drop_column('appointments', 'duration')
    op.drop_column('appointments', 'notes')
    op.drop_column('blocks', 'created_at')
    op.alter_column('working_hours', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('working_hours', 'hora_inicio',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('working_hours', 'hora_fim',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('working_hours', 'hora_fim',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('working_hours', 'hora_inicio',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('working_hours', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('blocks', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('date_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='appointmentstatus'),
               nullable=True)
    op.alter_column('appointments', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('appointments', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('appointments', 'observacoes')
    op.drop_column('appointments', 'duracao')
    op.drop_column('appointments', 'data_hora')
    # ### end Alembic commands ###
