"""Initial migration

Revision ID: 17547038e7ee
Revises: 
Create Date: 2026-02-08 16:32:48.165838

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '17547038e7ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('client_id', sa.Integer(), nullable=True))
    op.add_column('appointments', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='appointmentstatus'), nullable=True))
    op.add_column('appointments', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('appointments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('appointments', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('appointments', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'appointments', 'users', ['client_id'], ['id'])
    op.drop_column('appointments', 'client_name')
    op.drop_column('appointments', 'start_time')
    op.drop_column('appointments', 'client_email')
    op.drop_column('appointments', 'end_time')
    op.add_column('professionals', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('professionals', sa.Column('speciality', sa.String(), nullable=True))
    op.add_column('professionals', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('professionals', sa.Column('photo_url', sa.String(), nullable=True))
    op.add_column('professionals', sa.Column('address', sa.String(), nullable=True))
    op.add_column('professionals', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('professionals', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_professionals_email'), table_name='professionals')
    op.create_unique_constraint(None, 'professionals', ['user_id'])
    op.create_foreign_key(None, 'professionals', 'users', ['user_id'], ['id'])
    op.drop_column('professionals', 'email')
    op.drop_column('professionals', 'lunch_end')
    op.drop_column('professionals', 'work_start')
    op.drop_column('professionals', 'lunch_start')
    op.drop_column('professionals', 'work_end')
    op.drop_column('professionals', 'name')
    op.add_column('services', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('services', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('services', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('services', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('services', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('services', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('services', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.drop_column('services', 'duration_minutes')
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('type', sa.Enum('PROFESSIONAL', 'CLIENT', name='usertype'), nullable=False))
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('users', 'role')
    op.drop_column('users', 'number_phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('number_phone', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('role', postgresql.ENUM('professional', 'user', name='user_roles'), autoincrement=False, nullable=False))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'active')
    op.drop_column('users', 'type')
    op.drop_column('users', 'phone')
    op.add_column('services', sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('services', 'price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    op.alter_column('services', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('services', 'updated_at')
    op.drop_column('services', 'created_at')
    op.drop_column('services', 'active')
    op.drop_column('services', 'duration')
    op.drop_column('services', 'description')
    op.add_column('professionals', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('professionals', sa.Column('work_end', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('professionals', sa.Column('lunch_start', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('professionals', sa.Column('work_start', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('professionals', sa.Column('lunch_end', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('professionals', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'professionals', type_='foreignkey')
    op.drop_constraint(None, 'professionals', type_='unique')
    op.create_index(op.f('ix_professionals_email'), 'professionals', ['email'], unique=True)
    op.drop_column('professionals', 'updated_at')
    op.drop_column('professionals', 'created_at')
    op.drop_column('professionals', 'address')
    op.drop_column('professionals', 'photo_url')
    op.drop_column('professionals', 'description')
    op.drop_column('professionals', 'speciality')
    op.drop_column('professionals', 'user_id')
    op.add_column('appointments', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('client_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('client_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.alter_column('appointments', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'updated_at')
    op.drop_column('appointments', 'created_at')
    op.drop_column('appointments', 'notes')
    op.drop_column('appointments', 'status')
    op.drop_column('appointments', 'duration')
    op.drop_column('appointments', 'date_time')
    op.drop_column('appointments', 'client_id')
    # ### end Alembic commands ###
