"""Refactor WorkingHours

Revision ID: 35cd4915f458
Revises: 231149caa599
Create Date: 2026-02-16 20:15:04.891720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '35cd4915f458'
down_revision = '231149caa599'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('date_time', sa.DateTime(), nullable=False))
    op.add_column('appointments', sa.Column('duration', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('appointments', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'client_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('appointments', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='appointmentstatus'),
               nullable=True)
    op.drop_column('appointments', 'observacoes')
    op.drop_column('appointments', 'duracao')
    op.drop_column('appointments', 'data_hora')
    op.add_column('blocks', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('working_hours', sa.Column('day_of_week', sa.Integer(), nullable=False))
    op.add_column('working_hours', sa.Column('start_time', sa.Time(), nullable=False))
    op.add_column('working_hours', sa.Column('end_time', sa.Time(), nullable=False))
    op.add_column('working_hours', sa.Column('active', sa.Boolean(), nullable=True))
    op.alter_column('working_hours', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('working_hours', 'ativo')
    op.drop_column('working_hours', 'hora_inicio')
    op.drop_column('working_hours', 'dia_semana')
    op.drop_column('working_hours', 'hora_fim')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('working_hours', sa.Column('hora_fim', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('working_hours', sa.Column('dia_semana', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('working_hours', sa.Column('hora_inicio', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('working_hours', sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.alter_column('working_hours', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('working_hours', 'active')
    op.drop_column('working_hours', 'end_time')
    op.drop_column('working_hours', 'start_time')
    op.drop_column('working_hours', 'day_of_week')
    op.drop_column('blocks', 'created_at')
    op.add_column('appointments', sa.Column('data_hora', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('duracao', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('appointments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'CONFIRMED', 'CANCELLED', 'COMPLETED', name='appointmentstatus'),
               nullable=False)
    op.alter_column('appointments', 'service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('appointments', 'client_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('appointments', 'professional_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('appointments', 'notes')
    op.drop_column('appointments', 'duration')
    op.drop_column('appointments', 'date_time')
    # ### end Alembic commands ###
